# Generated by Django 3.2.6 on 2021-08-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='content',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sleepknowledge',
            name='content',
            field=models.CharField(max_length=40),
        ),
    ]
